packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  '@swc/core': true
  bcrypt: true
  cpu-features: true
  esbuild: true
  msw: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
